[build]
  command = "npm ci --prefer-offline || npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_VERSION = "10.9.2"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_STANDALONE = "true"
  NPM_CONFIG_LOGLEVEL = "error"
  NPM_CONFIG_PACKAGE_LOCK = "true"
